In [1]:
from cuml.datasets import make_blobs
from cuml.cluster import DBSCAN

# Create sample data
X, y = make_blobs(n_samples=100, centers=3, n_features=2, random_state=42)

# Fit clustering model
dbscan = DBSCAN(eps=1.0, min_samples=5)
dbscan.fit(X)
print(dbscan.labels_)

[-1  0  1  1  1  2  1  1  1  0  2  0  1  0  1  2  0  2  0 -1  0  0  0  0
  0  2  0  0  1 -1  1  0  0 -1  0  0  2  2  0  0  2  2  0  2  1  2  0  1
  0  0  0  1  2  0 -1  2  0 -1  1  1  2  0  1  0  0 -1  1 -1 -1  1  0  2
  1  2  2  1  1  2  2  0  0  1 -1  0  1  1  2  2  0  1  0  1  1  1  2  0
  2  1  2  0]


In [2]:
from cuml import LinearRegression
from cuml.datasets import make_regression
from cuml.model_selection import train_test_split

# Generate sample data directly in GPU memory
X, y = make_regression(n_samples=1000, n_features=4, noise=0.1, random_state=42)

# Split data into train and test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Fit model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
print(f"R² score: {model.score(X_test, y_test):.3f}")

R² score: 1.000


In [3]:
from cuml.datasets.classification import make_classification
from cuml.ensemble import RandomForestClassifier
from cuml.metrics import accuracy_score
from cuml.model_selection import train_test_split

# Generate synthetic data (binary classification task)
X, y = make_classification(
    n_classes=2,
    n_features=10,
    n_samples=1000,
    random_state=0
)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Initialize and train the model
random_forest = RandomForestClassifier(
    max_depth=10, n_estimators=25, random_state=0
).fit(X_train, y_train)

# Make predictions
predictions = random_forest.predict(X_test)

# Evaluate performance
score = accuracy_score(y_test, predictions)
print("Accuracy: ", score)

Accuracy:  0.976


In [4]:
from cuml.datasets import make_blobs
from cuml.manifold.umap import UMAP
from cuml.metrics import trustworthiness

# Generate synthetic blobs data
X_blobs, y_blobs = make_blobs(
    n_samples=1000,
    cluster_std=0.1,
    n_features=100,
    random_state=0,
)

# Initialize and train the UMAP model
umap = UMAP(n_neighbors=10).fit(X_blobs)

# Transform data to lower dimensions
X_embedded = umap.transform(X_blobs)

# Evaluate trustworthiness
score = trustworthiness(X_blobs, X_embedded)
print("Trustworthiness score: ", score)

Trustworthiness score:  0.8532907258064516


In [5]:
from cuml.cluster.dbscan import DBSCAN
from cuml.datasets import make_blobs
from cuml.metrics.cluster import adjusted_rand_score

# Generate synthetic blobs data
X_blobs, y_blobs = make_blobs(
    n_samples=1000,
    n_features=100,
    cluster_std=0.1,
    random_state=0,
)

# Initialize and train the DBSCAN model
dbscan = DBSCAN(eps=3, min_samples=2).fit(X_blobs)

# Get cluster predictions
predictions = dbscan.fit_predict(X_blobs)

# Evaluate clustering quality
score = adjusted_rand_score(y_blobs, predictions)
print("Adjusted random index score: ", score)

Adjusted random index score:  1.0


In [6]:
from cuml.datasets import make_regression
from cuml.linear_model import LinearRegression
from cuml.metrics import r2_score
from cuml.model_selection import train_test_split

# Generate synthetic regression data
X, y = make_regression(
    n_samples=2**10,
    n_features=100,
    n_informative=70,
    random_state=123,
)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

# Initialize and train the linear regression model
linear_regression = LinearRegression().fit(X_train, y_train)

# Make predictions
predictions = linear_regression.predict(X_test)

# Evaluate performance
score = r2_score(y_test, predictions)
print("R² score: ", score)

R² score:  1.0


In [7]:
from cuml.cluster import KMeans
from cuml.datasets import make_blobs

# Generate synthetic dataset for clustering
X, y = make_blobs(
    n_samples=50, n_features=10, centers=5, cluster_std=0.4, random_state=0
)
# Initialize and fit KMeans model
kmeans = KMeans(n_clusters=5).fit(X)

In [8]:
import pickle

# Save the fitted model to disk
with open("kmeans_model.pkl", "wb") as output_file:
    pickle.dump(kmeans, output_file, protocol=5)

In [9]:
# Load the model from disk
with open("kmeans_model.pkl", "rb") as input_file:
    kmeans_loaded_model = pickle.load(input_file)

# Display the loaded model's cluster centers
kmeans_loaded_model.cluster_centers_

array([[-4.3782754 ,  5.673881  , -5.809365  , -1.7014151 , -9.236413  ,
         0.6796301 ,  4.4793415 , -3.0451188 , -5.046296  ,  9.735212  ],
       [ 4.9611325 ,  8.417621  , -9.0796995 ,  9.357527  ,  8.626832  ,
        -1.2055869 ,  3.3610485 , -7.8263164 , -0.6502562 ,  0.46297693],
       [ 5.578274  , -3.9382834 ,  4.1194263 , -2.6670067 ,  3.6268754 ,
        -4.263903  , -3.6590233 ,  6.38936   , -7.029616  , -1.2048612 ],
       [-5.8457522 ,  2.362199  , -3.8079762 , -1.5414352 , -5.348188  ,
         7.406154  ,  2.9328313 ,  8.409007  ,  1.5656946 ,  1.231472  ],
       [-3.0099037 ,  4.276852  , -4.3493924 ,  2.3583264 ,  1.6495332 ,
        -2.6076655 , -5.1556067 , -1.7364906 , -7.954575  ,  2.6284964 ]],
      dtype=float32)

In [10]:
import joblib

joblib.dump(kmeans, "kmeans_model.joblib")

['kmeans_model.joblib']

In [11]:
kmeans_loaded_model = joblib.load("kmeans_model.joblib")
kmeans_loaded_model.cluster_centers_

array([[-4.3782754 ,  5.673881  , -5.809365  , -1.7014151 , -9.236413  ,
         0.6796301 ,  4.4793415 , -3.0451188 , -5.046296  ,  9.735212  ],
       [ 4.9611325 ,  8.417621  , -9.0796995 ,  9.357527  ,  8.626832  ,
        -1.2055869 ,  3.3610485 , -7.8263164 , -0.6502562 ,  0.46297693],
       [ 5.578274  , -3.9382834 ,  4.1194263 , -2.6670067 ,  3.6268754 ,
        -4.263903  , -3.6590233 ,  6.38936   , -7.029616  , -1.2048612 ],
       [-5.8457522 ,  2.362199  , -3.8079762 , -1.5414352 , -5.348188  ,
         7.406154  ,  2.9328313 ,  8.409007  ,  1.5656946 ,  1.231472  ],
       [-3.0099037 ,  4.276852  , -4.3493924 ,  2.3583264 ,  1.6495332 ,
        -2.6076655 , -5.1556067 , -1.7364906 , -7.954575  ,  2.6284964 ]],
      dtype=float32)

In [12]:
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

# Set up Dask cluster
cluster = LocalCUDACluster()
client = Client(cluster)

In [13]:
from cuml.dask.datasets import make_blobs
from cuml.dask.cluster import KMeans as DistributedKMeans

# Get number of workers
n_workers = client.scheduler_info()["n_workers"]

# Generate distributed dataset
X, y = make_blobs(
    n_samples=5000,
    n_features=30,
    centers=5,
    cluster_std=0.4,
    random_state=0,
    # 5 parts per worker to demonstrate distributed inference
    n_parts=n_workers * 5,
)

# Initialize and train the distributed KMeans model
distributed_kmeans = DistributedKMeans(n_clusters=5).fit(X)

In [14]:
# Extract single-GPU model and save it
combined_kmeans = distributed_kmeans.get_combined_model()

with open("kmeans_model.pkl", "wb") as output_file:
    pickle.dump(combined_kmeans, output_file, protocol=5)

In [15]:
# Load the single-GPU model
with open("kmeans_model.pkl", "rb") as input_file:
    combined_kmeans_loaded_model = pickle.load(input_file)

# Display the first 3 rows of the loaded model's cluster centers
combined_kmeans_loaded_model.cluster_centers_[:3]

array([[-4.644619  , -9.581896  ,  6.672268  ,  4.4319525 ,  2.1493733 ,
         2.5811942 ,  0.5911126 ,  6.239565  , -8.795231  , -0.38740197,
         9.801718  ,  7.5650883 ,  9.990776  , -5.8533907 , -1.2498875 ,
        -2.5379577 , -1.0481755 , -5.236915  , -9.304234  ,  4.632194  ,
        -0.09649599, -3.9311216 ,  6.1806536 , -7.429958  ,  5.661257  ,
        -8.542434  , -7.5206823 , -5.538724  ,  4.8289733 ,  2.5430906 ],
       [ 4.8198    ,  8.427117  , -9.216298  ,  9.382446  ,  8.491982  ,
        -1.0688543 ,  3.3341222 , -7.809988  , -0.5915902 ,  0.2628854 ,
         5.51485   , -4.099182  ,  4.2884803 , -2.842088  ,  3.634328  ,
        -4.1257997 , -3.5992334 ,  6.211796  , -6.9204736 , -1.0867236 ,
        -5.8400865 ,  2.223195  , -3.8685322 , -1.711388  , -5.3163548 ,
         7.6082335 ,  2.8888016 ,  8.524052  ,  1.57743   ,  1.0878687 ],
       [-6.942454  , -9.765983  , -6.532323  , -0.43099803,  6.1164665 ,
         3.72713   , -3.9550004 ,  6.1494174 , -1

In [16]:
import pickle

from cuml.cluster import KMeans
from cuml.datasets import make_blobs
from cuml.metrics.cluster import adjusted_rand_score

# Generate synthetic dataset for clustering
X, y = make_blobs(
    n_samples=1000, n_features=20, centers=5, cluster_std=0.5, random_state=42
)

# Train cuML KMeans
kmeans = KMeans(n_clusters=5, random_state=42).fit(X)

# Make predictions with cuML model
predictions = kmeans.predict(X)
score = adjusted_rand_score(y, predictions)
print(f"cuML KMeans ARI score: {score:.4f}")
print(f"cuML KMeans cluster centers shape: {kmeans.cluster_centers_.shape}")

cuML KMeans ARI score: 1.0000
cuML KMeans cluster centers shape: (5, 20)


In [17]:
# Convert cuML model to scikit-learn model
kmeans_sklearn = kmeans.as_sklearn()
print(f"Converted to scikit-learn model: {type(kmeans_sklearn)}")

# Save scikit-learn model to disk
pickle.dump(kmeans_sklearn, open("kmeans_model_sklearn.pkl", "wb"), protocol=5)
print("scikit-learn KMeans model saved with pickle")

Converted to scikit-learn model: <class 'sklearn.cluster._kmeans.KMeans'>
scikit-learn KMeans model saved with pickle


In [18]:
from cupy import asnumpy

# Load scikit-learn model and verify prediction quality
kmeans_loaded_sklearn = pickle.load(open("kmeans_model_sklearn.pkl", "rb"))
sklearn_predictions = kmeans_loaded_sklearn.predict(asnumpy(X))
sklearn_score = adjusted_rand_score(y, sklearn_predictions)
print(f"Loaded sklearn KMeans ARI score: {sklearn_score:.4f}")

Loaded sklearn KMeans ARI score: 1.0000


In [19]:
# Re-construct the cuML model from the scikit-learn model
kmeans_from_sklearn = KMeans.from_sklearn(kmeans_loaded_sklearn)
predictions = kmeans_from_sklearn.predict(X)
print("Re-constructed cuML KMeans ARI Score: ", adjusted_rand_score(y, predictions))

Re-constructed cuML KMeans ARI Score:  1.0


In [20]:
import numpy as np
from cuml.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# Load and prepare iris dataset
X, y = load_iris(return_X_y=True)
X, y = X.astype(np.float32), y.astype(np.int32)

# Train Random Forest model
random_forest = RandomForestClassifier(
    max_depth=3, random_state=0, n_estimators=10
).fit(X, y)

# Export cuML RF model as Treelite checkpoint
treelite_checkpoint_path = "./checkpoint.tl"
random_forest.as_treelite().serialize(treelite_checkpoint_path)

In [21]:
import treelite

# Load the Treelite model (checkpoint file has been copied over)
treelite_checkpoint_path = "./checkpoint.tl"
treelite_model = treelite.Model.deserialize(treelite_checkpoint_path)

# Make predictions using Treelite
predictions = treelite.gtil.predict(treelite_model, X, pred_margin=True)

In [26]:
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

# Create a local cluster with one worker per GPU
cluster = LocalCUDACluster()
client = Client(cluster)

# Display cluster information
print(f"Cluster dashboard available at: {client.dashboard_link}")

/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/distributed/node.py:188: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 44645 instead
  warnings.warn(


Cluster dashboard available at: http://127.0.0.1:44645/status


In [27]:
from cuml.dask.cluster import KMeans
from cuml.dask.datasets import make_blobs
from cuml.metrics import adjusted_rand_score

# Get number of workers for data partitioning
n_workers = len(client.scheduler_info()['workers'])

# Generate distributed synthetic data
X, y = make_blobs(
    n_samples=10000,
    n_features=20,
    centers=5,
    cluster_std=0.5,
    random_state=42,
    n_parts=n_workers * 2  # Multiple partitions per worker
)

print(f"Generated data with {len(X.to_delayed())} partitions")
print(f"Data type: {type(X)}")

Generated data with 2 partitions
Data type: <class 'dask.array.core.Array'>


In [28]:
# Train distributed K-Means
kmeans = KMeans(n_clusters=5, random_state=42)
kmeans.fit(X)

# Make predictions
labels = kmeans.predict(X)

# Evaluate clustering quality
score = adjusted_rand_score(y.compute(), labels.compute())
print(f"Adjusted Rand Score: {score:.4f}")

# View cluster centers
print(f"\nCluster centers shape: {kmeans.cluster_centers_.shape}")

Adjusted Rand Score: 1.0000

Cluster centers shape: (5, 20)


In [29]:
# Extract single-GPU model from distributed model
combined_model = kmeans.get_combined_model()

combined_model.predict(X)

array([0, 1, 2, ..., 3, 0, 4], shape=(10000,), dtype=int32)

In [30]:
import pickle


# Save the model
with open("kmeans_model.pkl", "wb") as f:
    pickle.dump(combined_model, f, protocol=5)

# Load and use the model
with open("kmeans_model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

print(f"Loaded model type: {type(loaded_model)}")
print(f"Model has {loaded_model.n_clusters} clusters")

Loaded model type: <class 'cuml.cluster.kmeans_mg.KMeansMG'>
Model has 5 clusters


In [31]:
from cuml.dask.ensemble import RandomForestClassifier
from cuml.dask.datasets import make_classification
from cuml.metrics import accuracy_score

# Generate classification dataset
n_samples = 5000
n_features = 30
n_classes = 3

X, y = make_classification(
    n_samples=n_samples,
    n_features=n_features,
    n_informative=int(n_features * 0.7),
    n_redundant=int(n_features * 0.2),
    n_classes=n_classes,
    random_state=42,
    n_parts=n_workers * 2
)

print(f"Generated classification dataset:")
print(f"  Samples: {n_samples}")
print(f"  Features: {n_features}")
print(f"  Classes: {n_classes}")
print(f"  Partitions: {len(X.to_delayed())}")

Generated classification dataset:
  Samples: 5000
  Features: 30
  Classes: 3
  Partitions: 2


In [32]:
# Train distributed Random Forest
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=16,
    n_bins=32,
    random_state=42
)

rf.fit(X, y)

# Make predictions
predictions = rf.predict(X)

# Evaluate accuracy
accuracy = accuracy_score(y.compute(), predictions.compute())
print(f"Training accuracy: {accuracy:.4f}")

/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/distributed/client.py:3375: UserWarning: Sending large graph of size 11.02 MiB.
This may cause some slowdown.
Consider loading the data with Dask directly
 or using futures or delayed objects to embed the data into the graph without repetition.
See also https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask for more information.
  warnings.warn(
[15:12:07] /__w/cuml/cuml/python/cuml/build/cp310-cp310-linux_x86_64/_deps/treelite-src/src/serializer.cc:202: The model you are loading originated from a newer Treelite version; some functionalities may be unavailable.
Currently running Treelite version 4.6.1
The model checkpoint was generated from Treelite version 4.7.0


Training accuracy: 1.0000


In [33]:
from cuml.dask.linear_model import LinearRegression
from cuml.dask.datasets import make_regression
from cuml.metrics import r2_score

# Generate regression dataset
X, y = make_regression(
    n_samples=10000,
    n_features=50,
    n_informative=40,
    random_state=42,
    n_parts=n_workers * 2
)

print(f"Generated regression dataset with {X.shape[0]:,} samples")

Generated regression dataset with 10,000 samples


In [34]:
# Train distributed Linear Regression
lr = LinearRegression()
lr.fit(X, y)

# Make predictions
predictions = lr.predict(X)

# Evaluate model
r2 = r2_score(y.compute(), predictions.compute())
print(f"R² score: {r2:.4f}")
print(f"Number of coefficients: {len(lr.coef_)}")

R² score: 1.0000
Number of coefficients: 50


In [35]:
import dask_cudf
import cudf

# Convert Dask Array to Dask DataFrame
# In practice, you'd often load data directly: dask_cudf.read_csv("data.csv")
X_computed = X.compute()
y_computed = y.compute()

# Create cuDF DataFrame
df = cudf.DataFrame(X_computed)
target = cudf.Series(y_computed)

# Convert to Dask DataFrame
ddf = dask_cudf.from_cudf(df, npartitions=n_workers * 2)
dtarget = dask_cudf.from_cudf(target, npartitions=n_workers * 2)

# Train with Dask DataFrame input
lr_df = LinearRegression()
lr_df.fit(ddf, dtarget)

print(f"Model trained successfully with Dask DataFrame input")
print(f"Predictions type: {type(lr_df.predict(ddf))}")

Model trained successfully with Dask DataFrame input
Predictions type: <class 'dask_cudf._expr.collection.Series'>
